### ISSUE TITLE
ModuleNotFoundError (packages out of sync?)

### ISSUE THREAD

**Issue by leebhoram** [XiaoXiao-Woo/PanCollection#5]
Hello! Thanks for sharing your code. These tools look useful. 

I was interested in running a script from `SSDiff` repo and encountered some errors from your other packages including this one, `PanCollection`. 
I managed to get around some trivial errors, but I got stuck on this one: 

``` shell
$ SSDiff_main# python image_train.py
trying to import PatchMergeModule
Traceback (most recent call last):
  File "/src/vision-robotics/SSDiff_main/image_train.py", line 92, in <module>
    main()
  File "/src/vision-robotics/SSDiff_main/image_train.py", line 41, in main
    args = parser_args()
  File "/src/vision-robotics/SSDiff_main/configs/option_DPM_pansharpening.py", line 20, in __init__
    from pancollection.configs.configs import panshaprening_cfg
ModuleNotFoundError: No module named 'pancollection.configs.configs'
```
As I navigate the folder `pancollection/configs/`, indeed no configs module is defined. (Also the spelling `panshaprening_cfg` looks wrong, by the way). Without a base config to start with, I can't keep trying running the script.

I guess that the versions of the dependent packages are out of sync by now. Would there be a quick fix for this or any chance of an update?

**Comment by XiaoXiao-Woo** [comment]
Thanks for your attention. Please refer to the following configs for running SSDiff:
```yaml
# GPL License
# Copyright (C) UESTC
# All Rights Reserved 
# @Author: Xiao Wu
# @reference: 

defaults:
- base: pansharpening
- datasets
- _self_


base:
  grad_clip_norm: 1
  img_range: 2047.0 # or adjust based on dataset_name
  debug: false
  test_samples_per_gpu: 1


# Dataset configuration
seed: 3407
samples_per_gpu: 32
workers_per_gpu: 0
resume_from: ""
dataset_type: "PanCollection" # "oldPan", "DLPan", "PanCollection", "Dummy"

dataset:
  train_name: "wv3"
  val_name: "wv3"
  test_name: "wv3"


# Evaluation
eval: false
direction: "maximize"


# Experimental description
experimental_desc: ""
model_type: "SSDiff"

ckpt_model_path: ""
model_path: "/path/to/your/model"
lr: 1e-3
lr_scheduler: true
crop_batch_size: 24
device: "cuda:0"
featEmbed: true


max_epochs: 12000
prox: "dot"
dim: 32
dim_head: 16
se_ratio_mlp: 0.5
se_ratio_rb: 0.5
ms_dim: 8
pan_dim: 1
model_channels: 128
schedule_sampler: "uniform"
lr_anneal_steps: 0
microbatch: -1
ema_rate: "0.9999"
use_fp16: false
fp16_scale_growth: 1e-3
image_size: 64
num_channels: 128
num_res_blocks: 2
num_heads: 4
num_heads_upsample: -1
attention_resolutions: "16,8"
dropout: 0.0
learn_sigma: false
sigma_small: false
class_cond: false
diffusion_steps: 1000
noise_schedule: "cosine"
timestep_respacing: "ddim1000"
use_kl: false
predict_xstart: true
rescale_timesteps: true
rescale_learned_sigmas: true
use_scale_shift_norm: false
use_checkpoint: false
log_interval: 100
save_interval: 1000
resume_checkpoint: ""
weight_decay: 0
clip_denoised: true
num_samples: 2047
use_ddim: true
```
